### ISSUE TITLE
BigInteger out of int range

### ISSUE THREAD

**Issue by DavePearce** [ConsenSys/evm-dafny#455]
A number of reference tests (e.g. `modexp_Berlin_0_2_0`) are failing because they generate the following exception:

```
java.lang.ArithmeticException: BigInteger out of int range
	at java.base/java.math.BigInteger.intValueExact(BigInteger.java:4792)
	at dafny.DafnySequence.Create(DafnySequence.java:123)
	at Bytes_Compile.__default.Padding(__default.java:68)
	at Bytes_Compile.__default.Slice(__default.java:64)
```

The essential issue here is that we are trying to create a _large_ sequence outside the bounds of a 32bit `int`.  This is a problem as Java arrays are limited in size to a 32bit `int`.

**Comment by DavePearce** [comment]
See [Issue#2859](https://github.com/dafny-lang/dafny/issues/2859) which examines this.
