### ISSUE TITLE
Updates for `GNUMakefile`

### ISSUE THREAD

**Issue by DavePearce** [Consensys/evm-dafny#586]
After #584, there are several outstanding issues with the `GNUMakefile`:

1. The testing component was deactivated in order to make progress on #584.  This needs to be restored.  It looks like there is some odd name clash arising.
2. The Dafny 4.0 CLI is largely implemented within the `GNUMakefile`, but not yet activated.  This should now be possible, given that the `build.gradle` is using it successfully now.

**Comment by henry-hz** [comment]
Hi @DavePearce , I am running `gradle build` and got:
```
~/code/evm-dafny master* ❯ gradle build                                                                                                                                   10:05:33

> Configure project :
DAFNY_HOME: /home/henry/.bin/dafny
Z3_PATH   : /home/henry/.bin/dafny/z3/bin/z3-4.8.5

> Task :compileDafny FAILED
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Microsoft.Dafny.Substituter.<>c__DisplayClass7_1.<Substitute>g__SubstituteForPattern|0(ExtendedPattern pattern)
   at Microsoft.Dafny.Substituter.Substitute(Expression expr)
   at Microsoft.Dafny.Translator.GetFunctionAxiom(Function f, Expression body, List`1 lits)
   at Microsoft.Dafny.Translator.AddFunctionAxiom(Function boogieFunction, Function f, Expression body)
   at Microsoft.Dafny.Translator.AddClassMember_Function(Function f)
   at Microsoft.Dafny.Translator.AddFunction_Top(Function f, Boolean includeAllMethods)
   at Microsoft.Dafny.Translator.AddClassMembers(TopLevelDeclWithMembers c, Boolean includeAllMethods, Boolean includeInformationAboutType)
   at Microsoft.Dafny.Translator.AddTypeDecl(RevealableTypeDecl d)
   at Microsoft.Dafny.Translator.DoTranslation(Program p, ModuleDefinition forModule)
   at Microsoft.Dafny.Translator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext()
   at Microsoft.Dafny.DafnyDriver.Translate(ExecutionEngineOptions options, Program dafnyProgram)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args)
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass10_0.<Main>b__0()
   at System.Threading.Thread.StartCallback()

FAILURE: Build failed with an exception.

* Where:
Build file '/home/henry/code/evm-dafny/build.gradle' line: 123

* What went wrong:
Execution failed for task ':compileDafny'.
> Process 'command 'dafny'' finished with non-zero exit value 134

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed
```

also manually I get the same error:

```
	dafny verify \
		--resource-limit 1000000 \
		--verify-included-files \
		--function-syntax 4 \
		--quantifier-syntax 4 \
		--solver-path $(HOME)/.bin/dafny/z3/bin/z3-4.8.5 \
		src/dafny/evm.dfy \
		src/dafny/evms/berlin.dfy
```

**Comment by DavePearce** [comment]
Hey Henry,

This is a bug in the Dafny compiler.  I have raise quite a few of these as issues (many of which have been fixed).  The first thing is to check your Dafny version.  If you're not using Dafny 4.2.0 then the first thing to do is upgrade Dafny.  If that still doesn't help, then we can try and triage what's going on.

**Comment by hmijail** [comment]
The Go backend support has been removed, so closing this.
