### ISSUE TITLE
Opcode Pattern Matching in evm.dfy

### ISSUE THREAD

**Issue by gaxiiiiiiiiiiii** [Consensys/evm-dafny#619]
### Description of the Issue
When opening the `evm.dfy` file, the following internal error occurs, preventing the file from functioning properly:
```
Dafny encountered an internal error. Please report it at <https://github.com/dafny-lang/dafny/issues>.
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Microsoft.Dafny.Substituter.<>c__DisplayClass7_1.<Substitute>g__SubstituteForPattern|0(ExtendedPattern pattern)
   at Microsoft.Dafny.Substituter.Substitute(Expression expr)
   at Microsoft.Dafny.Translator.GetFunctionAxiom(Function f, Expression body, List`1 lits)
   at Microsoft.Dafny.Translator.AddFunctionAxiom(Function boogieFunction, Function f, Expression body)
   at Microsoft.Dafny.Translator.AddClassMember_Function(Function f)
   at Microsoft.Dafny.Translator.AddFunction_Top(Function f, Boolean includeAllMethods)
   at Microsoft.Dafny.Translator.AddClassMembers(TopLevelDeclWithMembers c, Boolean includeAllMethods, Boolean includeInformationAboutType)
   at Microsoft.Dafny.Translator.AddTypeDecl(RevealableTypeDecl d)
   at Microsoft.Dafny.Translator.DoTranslation(Program p, ModuleDefinition forModule)
   at Microsoft.Dafny.Translator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.GetVerificationTasksAsync(DocumentAfterResolution document, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.PrepareVerificationTasksAsync(DocumentAfterResolution loaded, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.TranslateAsync()
```

### Attempted Solution
Modifying the code in `ExecuteBytecode` and `DeductGas` to use if-else statements instead of pattern matching resolved the issue.

Original Code
```dafny
function ExecuteBytecode(op: u8, st: ExecutingState): State {
   match op
      case STOP => Bytecode.Stop(st)
      case ADD => Bytecode.Add(st)
      ...
      case SELFDESTRUCT => Bytecode.SelfDestruct(st)
      case _ => ERROR(INVALID_OPCODE) 
}
```

Modified Code
```dafny
function ExecuteBytecode(op: u8, st: ExecutingState): State {
   if op == STOP then Bytecode.Stop(st)
   else if op == ADD then Bytecode.Add(st)
   ...
   else if op == SELFDESTRUCT then Bytecode.SelfDestruct(st)
   else ERROR(INVALID_OPCODE)
}
```

### Execution Environment
- Dafny: 4.4.0
- Z3: 4.12.4
- MacOS Monterey: 12.3
- VSCode: 1.85.1
- VSCode Dafny Extension: 3.2.2
- dotnet: 6.0.125

While the issue was resolved by switching from pattern matching to if-else statements, the underlying cause remains unclear. Therefore, I am reporting this for further investigation.

**Comment by DavePearce** [comment]
Hi @gaxiiiiiiiiiiii ,

So, this is a Dafny bug of some kind and we often see this with new releases of Dafny.  There was a very similar issue with Dafny 4.3.0 which appears to have been fixed.  In actual fact, I cannot recreate this on my (Linux) machine.  I will try on the MacBook and see whether it shows up there.

It seems that, since you are running Z3 `4.12.4` you have supplied some additional command-line arguments to Dafny.  Are there any other command-line arguments you are using?

**Comment by DavePearce** [comment]
There is [one related](https://github.com/dafny-lang/dafny/issues/4894) open issue on the Dafny repo it seems.

**Comment by DavePearce** [comment]
So, I'm not recreating this on my M1 macbook either.  My setup is pretty much identical to what you have, so the only real difference is the version of Z3 (`4.12.1` which is the default).  Can we rule that out first as the reason?  The error doesn't suggest to me that it would be Z3, but we need to rule it out first.

Also, if there are any other changes you've made to the code base etc, then let me know.

**Comment by gaxiiiiiiiiiiii** [comment]
Thank you for your response. Upon further review, I realized that my execution environment was using `z3-12.4.1`.

This is because, although the Dafny installed via homebrew depends on `z3-12.4.4`, it seems that the VScode extension is using a separately built `z3-12.4.1`.

In my environment, the bug was reproduced with the code that has not been modified at all. If you can think of anything else I should check or try, please let me know.

**Comment by DavePearce** [comment]
Hey @gaxiiiiiiiiiiii , ok well that's helpful to know.  Hmmmm, yeah its an interesting one.  Can you let me know the git hash for the evm-dafny you see this problem on?  I'll have a look and see whether there are any other differences on my macbook.

**Comment by DavePearce** [comment]
Ok, so I went back and looked for [the issue](https://github.com/dafny-lang/dafny/issues/4214) we previously had that was like this.  To be honest, this looks extremely similar to the issue you are reporting.  The stack trace reported in that issue:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'source'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Microsoft.Dafny.Substituter.<>c__DisplayClass7_1.<Substitute>g__SubstituteForPattern|0(ExtendedPattern pattern)
   at Microsoft.Dafny.Substituter.Substitute(Expression expr)
   at Microsoft.Dafny.Translator.GetFunctionAxiom(Function f, Expression body, List`1 lits)
   at Microsoft.Dafny.Translator.AddFunctionAxiom(Function boogieFunction, Function f, Expression body)
   at Microsoft.Dafny.Translator.AddClassMember_Function(Function f)
   at Microsoft.Dafny.Translator.AddFunction_Top(Function f, Boolean includeAllMethods)
   at Microsoft.Dafny.Translator.AddClassMembers(TopLevelDeclWithMembers c, Boolean includeAllMethods, Boolean includeInformationAboutType)
   at Microsoft.Dafny.Translator.AddTypeDecl(RevealableTypeDecl d)
```

**Comment by gaxiiiiiiiiiiii** [comment]
Upon checking the VSCode extension settings, I realized I was using Dafny version `4.1.0`. Sorry for the incorrect info initially. After updating to `4.4.0`, the issue is resolved. Thanks for the help and patience. I'm closing this thread now.

**Comment by DavePearce** [comment]
All good ... glad we got it resolved!
